type: object
description: |
    Handler that returns HTTP 200 if file exist
    and returns file data with mapped content/type
additionalProperties: false
properties:
    fs-cache-component:
        type: string
        description: Name of the FsCache component
        defaultDescription: fs-cache-component
    expires:
        type: string
        description: Cache age in seconds
        defaultDescription: 600
    directory-file:
        type: string
        description: File to return for directory requests. File name (not path) search
            in requested directory
        defaultDescription: index.html
    not-found-file:
        type: string
        description: File to return for missing files
        defaultDescription: /404.html
